# Generated by Django 4.1.7 on 2023-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_products_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate_seller',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='products',
            name='shop_link',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='logo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
