# Generated by Django 4.1.7 on 2023-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_products_rate_seller_products_shop_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fk_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
