# Generated by Django 4.1.7 on 2023-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_alter_products_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.CharField(max_length=1000),
        ),
    ]
