# Generated by Django 4.1.7 on 2023-03-25 11:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=18, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('born_date', models.DateField()),
                ('id_hash', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
