# Generated by Django 4.1.7 on 2023-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
