# Generated by Django 4.1.7 on 2023-06-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0003_users_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_photo',
        ),
    ]
